version: '3'

services:
  registry:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  configuration:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  journal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  directory:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  postman:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"