version: '3'

services:
  registry:
    image: parameshg/matrix.registry
    build:
      context: .
      dockerfile: Matrix.Agent.Registry/docker-compose.yml

  configuration:
    image: parameshg/matrix.configuration
    build:
      context: .
      dockerfile: Matrix.Agent.Configurator/docker-compose.yml

  journal:
    image: parameshg/matrix.journal
    build:
      context: .
      dockerfile: Matrix.Agent.Journal/docker-compose.yml

  directory:
    image: parameshg/matrix.directory
    build:
      context: .
      dockerfile: Matrix.Agent.Directory/docker-compose.yml

  postman:
    image: parameshg/matrix.postman
    build:
      context: .
      dockerfile: Matrix.Agent.Postman/docker-compose.yml

  web:
    image: parameshg/matrix.web
    build:
      context: .
      dockerfile: Matrix.Web/docker-compose.yml

  api:
    image: parameshg/matrix.api
    build:
      context: .
      dockerfile: Matrix.Api/docker-compose.yml